{
    "name": "Icons for Apps",
    "description": """Minimalist and elegant icons for apps""",
    "category": "Themes/Backend",
    "version": "14.0.1.1.2",
    'author': 'BIKO Solutions',
    'company': 'BIKO Solutions',
    'maintainer': 'BIKO Solutions',
    "depends": ['base', 'base_setup'],
    "data": [
        'views/icons.xml',
        'views/res_config_settings_view.xml',
    ],
    'license': 'LGPL-3',
    'pre_init_hook': 'test_pre_init_hook',
    'post_init_hook': 'test_post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
}
